### ISSUE TITLE
Возможность хранить папки и другие файлы рядом со схемами 

### ISSUE THREAD

**Issue by tsapko3628** [eonae/nodejs-toolbox#3]
Сейчас в папке со схемами, путь до которой указывается в аргументах, можно хранить только сами схемы. Если в папке есть файл с названием которое не подходит по `schema-x.x.x.json`, будет выброшена ошибка. Если там будет папка с подходящим названием, будет также ошибка. Было бы удобно иметь возможность хранить папки рядом со схемами и указывать ref-ы на схемы в этой папке. Предлагаю игнорировать при поиске схем файлы, не подходящие по названию, и папки

**Comment by eonae** [comment]
Fixed. All files and folder not matching pattern will be just ignored.
